### ISSUE TITLE
[suggestion] 패턴 디자인 1주차 시작했습니다 ^^

### ISSUE THREAD

**Issue by dev210202** [riyenas0925/Design_Pattern#5]
패턴 디자인 1주차 시작했습니다 ^^
https://github.com/jkey20/IF_Pattern
여기서 0. why?.md 읽어보시고 1주차 hwp파일 읽어보시구 한번 해보시는걸 추천드립니다 물론 이건 JAVA로 하는 것

**Comment by riyenas0925** [comment]
@jkey20 같이 하면 재밌을것 같은데 내가 시간대가 일정하지 않아서 ㅋㅋㅋ 따로 할라고

**Comment by riyenas0925** [comment]
@jkey20 근디 누구누구 참여하는거?? 남훈이도 참여하는건가?

**Comment by dev210202** [comment]
아마 나무니도 할거같아
시간대 힘든거 아니까 참여하라는건 아니고 여기 페이지에 주차마다 올라오는거 한번 따라해보면서 다른사람들 올린것들이랑 피드백들 보면서 같이 따라해보라고 올려봤스
MVC패턴만 하긴하지만 도움 될거같아서..?

**Comment by riyenas0925** [comment]
@jkey20 ㅇㅎㅇㅎ 그렇구만 자바면 Junit으로 테스트 하면서 공부하는것도 좋을것 같네
